/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzarendeles;

import javax.swing.JOptionPane;

/**
 *
 * @author Adrikahhhh
 */
public class PizzaRendelo extends javax.swing.JFrame {

    /**
     * Creates new form PizzaRendelo
     */
    public PizzaRendelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BtnRendeles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSzoszSonkas = new javax.swing.JLabel();
        lblMeretSonkas = new javax.swing.JLabel();
        spinnerSonkas = new javax.swing.JSpinner();
        lblSonkasKukoricas = new javax.swing.JLabel();
        cmbMeretSonkas = new javax.swing.JComboBox<>();
        cmbSzoszSonkas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblSzoszSzalamis = new javax.swing.JLabel();
        lblMeretSzalamis = new javax.swing.JLabel();
        spinnerSzalamis = new javax.swing.JSpinner();
        lblSzalamisSajtos = new javax.swing.JLabel();
        cmbMeretSzalamis = new javax.swing.JComboBox<>();
        cmbSzoszSzalamis = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblSzosz2 = new javax.swing.JLabel();
        lblMeret2 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        cmboxMeret2 = new javax.swing.JComboBox<>();
        cmboxSzosz2 = new javax.swing.JComboBox<>();
        BtnMegse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BtnRendeles.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BtnRendeles.setText("Rendelés leadása");
        BtnRendeles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRendelesMouseEntered(evt);
            }
        });
        BtnRendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRendelesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Megjegyzés:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel5.setText("Pizza Gui");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblSzoszSonkas.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSzoszSonkas.setText("Szósz:");

        lblMeretSonkas.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMeretSonkas.setText("Méret:");

        spinnerSonkas.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        spinnerSonkas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));
        spinnerSonkas.setBorder(null);

        lblSonkasKukoricas.setText("Sonkás kukoricás");

        cmbMeretSonkas.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cmbMeretSonkas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nincs méret kiválasztva!", "32 cm  Ár:1490 Ft", "45 cm  Ár: 2290 Ft", "60 cm  Ár: 4390 Ft" }));
        cmbMeretSonkas.setBorder(null);
        cmbMeretSonkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMeretSonkasActionPerformed(evt);
            }
        });

        cmbSzoszSonkas.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cmbSzoszSonkas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alapszósz: Paradicsomos", "Fokhagymás szósz", "Tzaziki szósz" }));
        cmbSzoszSonkas.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSonkasKukoricas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinnerSonkas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMeretSonkas)
                            .addComponent(lblSzoszSonkas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSzoszSonkas, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMeretSonkas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerSonkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSonkasKukoricas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMeretSonkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeretSonkas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSzoszSonkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSzoszSonkas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblSzoszSzalamis.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSzoszSzalamis.setText("Szósz:");

        lblMeretSzalamis.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMeretSzalamis.setText("Méret:");

        spinnerSzalamis.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        spinnerSzalamis.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));
        spinnerSzalamis.setBorder(null);

        lblSzalamisSajtos.setText("Szalámis sajtos");

        cmbMeretSzalamis.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cmbMeretSzalamis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nincs méret kiválasztva!", "45 cm  Ár: 2290 Ft", "60 cm  Ár: 4390 Ft" }));
        cmbMeretSzalamis.setBorder(null);
        cmbMeretSzalamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMeretSzalamisActionPerformed(evt);
            }
        });

        cmbSzoszSzalamis.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cmbSzoszSzalamis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alapszósz: Paradicsomos", "Fokhagymás szósz", "Tzaziki szósz" }));
        cmbSzoszSzalamis.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSzalamisSajtos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinnerSzalamis, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMeretSzalamis)
                            .addComponent(lblSzoszSzalamis, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSzoszSzalamis, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMeretSzalamis, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerSzalamis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSzalamisSajtos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMeretSzalamis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeretSzalamis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSzoszSzalamis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSzoszSzalamis))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblSzosz2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSzosz2.setText("Szósz:");
        lblSzosz2.setEnabled(false);

        lblMeret2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblMeret2.setText("Méret:");
        lblMeret2.setEnabled(false);

        jSpinner5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jSpinner5.setBorder(null);
        jSpinner5.setEnabled(false);

        jLabel7.setText("Magyaros");
        jLabel7.setEnabled(false);

        cmboxMeret2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cmboxMeret2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nincs méret kiválasztva!", "32 cm", "45 cm", "60 cm" }));
        cmboxMeret2.setBorder(null);
        cmboxMeret2.setEnabled(false);
        cmboxMeret2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxMeret2ActionPerformed(evt);
            }
        });

        cmboxSzosz2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cmboxSzosz2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nincs szósz kiválasztva!", "Paradicsomos szósz", "Fokhagymás szósz", "Tzaziki szósz" }));
        cmboxSzosz2.setBorder(null);
        cmboxSzosz2.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMeret2)
                            .addComponent(lblSzosz2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmboxSzosz2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmboxMeret2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboxMeret2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeret2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboxSzosz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSzosz2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        BtnMegse.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BtnMegse.setText("Mégse");
        BtnMegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMegseActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PizzaKepek/sonka kukorica 3.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PizzaKepek/magyaros 3.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PizzaKepek/szalámis.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnRendeles)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRendeles, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRendelesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRendelesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRendelesMouseEntered

    private void cmbMeretSonkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMeretSonkasActionPerformed
        String meret = (String) cmbMeretSonkas.getSelectedItem();
        JOptionPane.showMessageDialog(rootPane, "A kiválasztott méret: "  +meret);
        
          
        
    }//GEN-LAST:event_cmbMeretSonkasActionPerformed

    private void cmbMeretSzalamisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMeretSzalamisActionPerformed
        String meret = (String) cmbMeretSzalamis.getSelectedItem();
        JOptionPane.showMessageDialog(rootPane, "A kiválasztott méret: "  +meret);
    }//GEN-LAST:event_cmbMeretSzalamisActionPerformed

    private void cmboxMeret2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxMeret2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboxMeret2ActionPerformed

    private void BtnRendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRendelesActionPerformed
        
        boolean vanMeretValasztvaSonkas = cmbMeretSonkas.getSelectedIndex() >0;
        boolean vanMeretValasztvaSzalamis = cmbMeretSzalamis.getSelectedIndex() > 0;
        
        String uzenet, cim = "Sikeres rendelés";
        
        if (vanMeretValasztvaSonkas || vanMeretValasztvaSzalamis){
     
            cim += " - méret megadva!";
            uzenet = "A rendelést sikeresen rögzítettük!";
        }else {
            cim = "HIBA";
            uzenet = "Nincs méret kiválasztva!";   
        }
        
        int sonkasErtek = (int) spinnerSonkas.getValue();
        int szalamisErtek = (int) spinnerSzalamis.getValue();
        
        if (sonkasErtek == 0 && szalamisErtek == 0){
            JOptionPane.showMessageDialog(null, "0 db Pizza nem rendelhető!");
            
    
        }else{
            JOptionPane.showMessageDialog(null, "Rendelés leadva! ");
        }
        JOptionPane.showMessageDialog(null, uzenet, cim, 0);
        
    }//GEN-LAST:event_BtnRendelesActionPerformed

    private void BtnMegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMegseActionPerformed

        System.exit(0);
    }//GEN-LAST:event_BtnMegseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaRendelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaRendelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMegse;
    private javax.swing.JButton BtnRendeles;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbMeretSonkas;
    private javax.swing.JComboBox<String> cmbMeretSzalamis;
    private javax.swing.JComboBox<String> cmbSzoszSonkas;
    private javax.swing.JComboBox<String> cmbSzoszSzalamis;
    private javax.swing.JComboBox<String> cmboxMeret2;
    private javax.swing.JComboBox<String> cmboxSzosz2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblMeret2;
    private javax.swing.JLabel lblMeretSonkas;
    private javax.swing.JLabel lblMeretSzalamis;
    private javax.swing.JLabel lblSonkasKukoricas;
    private javax.swing.JLabel lblSzalamisSajtos;
    private javax.swing.JLabel lblSzosz2;
    private javax.swing.JLabel lblSzoszSonkas;
    private javax.swing.JLabel lblSzoszSzalamis;
    private javax.swing.JSpinner spinnerSonkas;
    private javax.swing.JSpinner spinnerSzalamis;
    // End of variables declaration//GEN-END:variables
}
